project:
  type: book
  output-dir: docs
book:
  title: Introduction to Data Science with R
  author:
    name: Florian Hartig, Melina de Souza Leite, Lisa Hülsmann, Alexandra Koch, Magdalena Mair, and Maximilian Pichler
  date: March 2025
  site-url: https://TheoreticalEcology.github.io/DataScienceInR/
  repo-url: https://github.com/TheoreticalEcology/DataScienceInR
  repo-branch: master
  repo-actions: edit
  sharing:
  - twitter
  - facebook
  - linkedin
  chapters:
  - index.qmd
  - 0-Introduction.qmd
  - 0-GettingStarted.qmd
  - part: Data input and manimulation
    chapters:
    - 1A-basicOperations.qmd    
    - 1B-PreparingData.qmd
    - 1C-Exercise.qmd
  - part: Descriptive Statistics
    chapters:
    - 2A-DescriptiveStatistics.qmd
    - 2B-SummaryStatistics.qmd
    - 2A-Exercise.qmd
  - part: Hypothesis Testing
    chapters:
    - 3A-NHST.qmd
    - 3B-HypothesisTests.qmd
    - 3A-Exercise.qmd
  - part: Regression Analysis
    chapters:
    - 4-SimpleRegression.qmd
    - 5-MultipleRegression.qmd
    - 6-GLM.qmd
    - 4A-Exercise.qmd
    - 5A-Exercise.qmd
    - 6A-Exercise.qmd
  - part: Multivariate Statistics
    chapters:
    - 7A-Multivariate.qmd
    - 7B-Exercise.qmd
  - part: Predictive Modeling
    chapters: 
    - 8-MachineLearning.qmd
    - 8A-Exercise.qmd
  - part: Experimental Design
    chapters: 
    - 9-Design.qmd
  - part: Data Science Skills
    chapters:
    - 10-DataWrangling.qmd
    - 11-Reproducibility.qmd
  appendices: 
    - 13A-regressions.qmd
engine: knitr
google-scholar: true
execute:
  freeze: auto
  cache: false
knitr:
  opts_chunk:
    collapse: true
format:
  html:
    code-copy: hover
    theme: 
      light: [cosmo, question.css]
      dark: [cosmo, question.css]
    css: include/webex.css
    include-after-body: include/webex.js
editor: visual